name: CI/CD 2 AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #- name: Run tests
      #  run: pytest

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            source venv/bin/activate
            cd /home/ubuntu/02.LLMBasedlaCDriftAnalyzer
            git fetch --all
            git reset --hard origin/main
            git pull origin main
            python3 -m venv venv
            pip install -r requirements.txt
            export AWS_ACCESS_KEY_ID=AKIAWTTKELUZWKUVFSNU
            export AWS_SECRET_ACCESS_KEY=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
            export api_key=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
            terraform init
            ##terraform apply
            terraform plan -out=plan.tfplan
            terraform show -json plan.tfplan > plan.json
            python3 main.py